Feature/add pre commit formatter for php
tech-quest/docker-template pull request #6
Opened 2021-12-13 23:38 UTC by Ohmiya-Mizuki

2021-12-14 23:55 UTC, orihikadichu requested changes

2021-12-14 23:55 UTC, orihikadichu commented on src/sample.php
> +}
このサンプルファイルは削除してもらえれば！！

2021-12-15 23:08 UTC, Ohmiya-Mizuki commented
gitignoreに入れるべきファイルがあまり理解できてないです！💦
yarn.lockを入れた方が良いのか？って感じです！
conventional commitsしてみました！

2021-12-15 23:21 UTC, orihikadichu requested changes

2021-12-15 23:21 UTC, orihikadichu commented on yarn.sh
> +    [ $COUNT_DOCKER_IMAGE == "0" ]; then
ここは改行なしでお願いします！

2021-12-16 00:02 UTC, orihikadichu approved these changes
![LGTM](https://image.lgtmoon.dev/108554)

2021-12-16 23:54 UTC, merged